defaults:
  - _self_
  - env: duckietown
  - override hydra/launcher: submitit_local

# task settings
discount: 0.99
# train settings
num_seed_frames: 4000
num_train_frames: 2000000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 500000
replay_buffer_num_workers: 1
nstep: 3
batch_size: 128
# misc
seed: 1
device: cuda
use_tb: True
save_video: true
save_train_video: false
# experiment
# agent

agent:
  _target_: src.agents.drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  critic_lr: 0.0001
  actor_lr: 0.000000005
  encoder_lr: 0.0001
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: 50
  stddev_schedule: linear(0.1,0.01,5000000) #${stddev_schedule}
  stddev_clip: 0.02
  normalize_obs: True

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
