defaults:
  - env: duckietown
  - _self_

episodes: 50
outdir: /workspaces/duckietown-irl/eval_results
device: "cuda"
env:
  full_transparency: True


agent:
  _target_: src.agents.drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  critic_lr: 0.0001
  actor_lr: 0.000000005
  encoder_lr: 0.001
  critic_target_tau: 0.01
  update_every_steps: 2
  is_constraint: True
  use_tb: False
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: 50
  stddev_schedule: linear(0.1,0.01,5000000) #${stddev_schedule}
  stddev_clip: 0.02

policy_path: '/workspaces/duckietown-irl/policies/snapshot_6400.pt'
