defaults:
  - env: duckietown
  - _self_

num_trajs: 50
save_path: null

agent:
  _target_: src.agents.drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  hidden_dim: 1024
  feature_dim: 50
